### ISSUE TITLE
Make the navbar responsive

### ISSUE THREAD

**Issue by yp969803** [fordevio/wharf#16]
ref file: https://github.com/fordevio/wharf/blob/main/client/src/components/Navbar/index.tsx

**Comment by HarshikaAdarsh** [comment]
Hey, is anyone working on this issue.
I would like to work on it.

**Comment by yp969803** [comment]
@HarshikaAdarsh are you working in this issue?

**Comment by HarshikaAdarsh** [comment]
yes @yp969803

**Comment by HarshikaAdarsh** [comment]
Hi @yp969803 , 

I have created a PR for this issue. Please review the changes and let me know if any modification are required.

Thanks!
