### ISSUE TITLE
Refactor design of containerDetail page, ,make it responsive

### ISSUE THREAD

**Issue by yp969803** [fordevio/wharf#24]
ref code: https://github.com/fordevio/wharf/tree/main/client/src/pages/ContainerInside/Detail

start a container with the below command:
```
sudo docker volume create wharf_vol
sudo docker network create wharf_net
sudo docker run -d --name my-nginx -p 80:80 --network wharf-net -v ./demo:/demo -v wharf_vol:./new_demo nginx

```

**Comment by anveshthakur** [comment]
Hi @yp969803, I'd like to work on this.

Thanks!

**Comment by yp969803** [comment]
@anveshthakur thanks for the interest in the issue
